from __future__ import annotations

import hashlib
from dataclasses import asdict, dataclass
from pathlib import Path

from .emitter import BuildManifest
from .io import atomic_write_bytes


GENERATED_MARKER = b"# Generated by RenWeave."


@dataclass(slots=True)
class InstallManifest:
    schema_version: int
    language: str
    destination: str
    installed_files: list[str]

    def to_dict(self) -> dict:
        return asdict(self)


class TranslationInstaller:
    """Install generated scripts without silently replacing user-owned files."""

    def install(
        self,
        build: BuildManifest,
        game_dir: str | Path,
        *,
        overwrite_existing: bool = False,
    ) -> InstallManifest:
        source = Path(build.output_dir).expanduser().resolve()
        game = Path(game_dir).expanduser().resolve()
        if not source.is_dir():
            raise FileNotFoundError(f"构建输出不存在：{source}")
        if not game.is_dir() or game.name.casefold() != "game":
            raise ValueError(f"安装目标不是 Ren'Py game 目录：{game}")
        destination = game / "tl" / build.renpy_language
        plan: list[tuple[Path, Path, bytes]] = []
        manifest_prefix = Path("game") / "tl" / build.renpy_language
        for record in build.files:
            manifest_path = Path(record.relative_path)
            try:
                relative = manifest_path.relative_to(manifest_prefix)
            except ValueError as exc:
                raise ValueError(f"构建清单包含语言目录外的文件：{record.relative_path}") from exc
            path = source / relative
            if not path.is_file():
                raise FileNotFoundError(f"构建清单文件不存在：{path}")
            payload = path.read_bytes()
            if hashlib.sha256(payload).hexdigest() != record.sha256:
                raise ValueError(f"构建文件哈希与清单不一致：{path}")
            target = destination / relative
            plan.append((relative, target, payload))
            if not target.is_file():
                continue
            existing = target.read_bytes()
            if existing == payload or overwrite_existing or existing.startswith(GENERATED_MARKER):
                continue
            raise FileExistsError(
                f"拒绝覆盖非 RenWeave 文件：{target}；如确认替换，请使用 --overwrite-existing"
            )

        installed: list[str] = []
        for relative, target, payload in plan:
            if target.is_file():
                existing = target.read_bytes()
                if existing == payload:
                    installed.append(relative.as_posix())
                    continue
            atomic_write_bytes(target, payload)
            installed.append(relative.as_posix())
        return InstallManifest(
            schema_version=1,
            language=build.renpy_language,
            destination=str(destination),
            installed_files=installed,
        )
